services:

  mlflow-tracking-server:
    image: ghcr.io/mlflow/mlflow
    command: mlflow ui --port 5000 --host 0.0.0.0 --backend-store-uri ./mlruns --artifacts-destination ./mlruns
    volumes:
      - ./mlruns:/mlruns
    container_name: mlflow-tracking
    ports:
      - 5000:5000

  lending-prediction-service:
    build:
      context: .
      dockerfile: Dockerfile.Service
      tags:
        - lending-prediction-service:latest
        - ghcr.io/joaopfribeiro/oml_rumos_bank_service:latest
    image: lending-prediction-service
    container_name: lending-prediction-service
    ports:
      - 5002:5002
